cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

packages:
  - 'cli-aliases/*'
  - 'packages/*'
  - 'examples/custom-cli/*'
  - 'examples/custom-cli/*/customized-ui'
