cleanupUnusedCatalogs: true
linkWorkspacePackages: true
preferWorkspacePackages: true

packages:
  - 'cli/*'
  - 'packages/*'
  - 'frameworks/*'
  - 'examples/custom-cli/*'
  - 'examples/custom-cli/*/customized-ui'
