/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MotorcyclesMotorcycleIdRouteImport } from './routes/motorcycles/$motorcycleId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MotorcyclesMotorcycleIdRoute = MotorcyclesMotorcycleIdRouteImport.update({
  id: '/motorcycles/$motorcycleId',
  path: '/motorcycles/$motorcycleId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/motorcycles/$motorcycleId': typeof MotorcyclesMotorcycleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/motorcycles/$motorcycleId': typeof MotorcyclesMotorcycleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/motorcycles/$motorcycleId': typeof MotorcyclesMotorcycleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/motorcycles/$motorcycleId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/motorcycles/$motorcycleId'
  id: '__root__' | '/' | '/motorcycles/$motorcycleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MotorcyclesMotorcycleIdRoute: typeof MotorcyclesMotorcycleIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motorcycles/$motorcycleId': {
      id: '/motorcycles/$motorcycleId'
      path: '/motorcycles/$motorcycleId'
      fullPath: '/motorcycles/$motorcycleId'
      preLoaderRoute: typeof MotorcyclesMotorcycleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MotorcyclesMotorcycleIdRoute: MotorcyclesMotorcycleIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
